version: '3'

services:
  webapp:
    container_name: laravel
    build: ./docker
    volumes:
      - './:/var/www/html'
    networks:
      - website

  nginx:
    image: nginx:alpine
    container_name: laravelserver
    ports:
      - '8000:8000'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
    networks:
      - website

  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123123
      - MYSQL_DATABASE=laravel
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  website:

volumes:
  mysql_data: { driver: local }



